spring.application.name=insurance-review-support

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=INS_ADMIN
spring.datasource.password=InsAdmin123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp