spring.application.name=insurance-review-support

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=myoracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp